# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Vendedores Unidos
#email: your-email@example.com
#description for the website. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
description: >- # this means to ignore newlines until "baseurl:"
  We are a coalition of street vendors in Washington, D.C. Our passion is to serve our community. 
  Many of us do this by vending cultural foods. Other vendors sell clothing, lotions, and even face masks. 
  Together, we are United Vendors active in the community to enrich it with culture and to help it grow the economy.
  Somos una coalición de vendedores ambulantes en Washington, D.C. 
  Nuestra pasión es servir a nuestra comunidad. 
  Muchos de nosotros hacemos esto vendiendo comida culturales. 
  Otros vendedores venden ropa, lociones e incluso máscaras. 
  Juntos, somos Vendedores Unidos activos en la comunidad para llenarla con cultura y ayudar a crecer la economía.
#baseurl: "" # the subpath of your site, e.g. /blog
# the base hostname & protocol for your site, e.g. http://example.com
url: "https://unitedvendorsdc.github.io" 
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#theme: creative-theme-jekyll
markdown: kramdown
#plugins:
  #- jekyll-feed
permalink: /:title

defaults: 
  - 
    scope: 
      path: "" 
      type: "posts" 
    values: 
      layout: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-cayman